### ISSUE TITLE
Fails to run regression test with error  read error: invalid block type and  Cause: java.util.zip.ZipException: invalid block type

### ISSUE THREAD

**Issue by francisbrosnan** [ASPLes/reactive-myqtt-http-api#1]
When running regression test:
`>> testOnly MyQttHttpApiSpec -- -z "004" 
`
..it fails with:

```
[info]   com.typesafe.config.ConfigException$IO: reference.conf @ jar:file:/home/acinom/.ivy2/local/es.aspl.reactive/reactive-myqtt_2.12/0.17.389/jars/reactive-myqtt_2.12.jar!/reference.conf: read error: invalid block type
[info]   at com.typesafe.config.impl.Tokenizer$TokenIterator.nextCharRaw(Tokenizer.java:159)
[info]   at com.typesafe.config.impl.Tokenizer$TokenIterator.nextCharAfterWhitespace(Tokenizer.java:211)
[info]   at com.typesafe.config.impl.Tokenizer$TokenIterator.pullNextToken(Tokenizer.java:579)
[info]   at com.typesafe.config.impl.Tokenizer$TokenIterator.queueNextToken(Tokenizer.java:660)
[info]   at com.typesafe.config.impl.Tokenizer$TokenIterator.next(Tokenizer.java:678)
[info]   at com.typesafe.config.impl.Tokenizer$TokenIterator.next(Tokenizer.java:63)
[info]   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.popToken(ConfigDocumentParser.java:45)
[info]   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.nextToken(ConfigDocumentParser.java:51)
[info]   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:619)
[info]   at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
[info]   ...
[info]   Cause: java.util.zip.ZipException: invalid block type
[info]   at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
[info]   at java.io.FilterInputStream.read(FilterInputStream.java:133)
[info]   at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
[info]   at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
[info]   at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[info]   at java.io.InputStreamReader.read(InputStreamReader.java:184)
[info]   at java.io.BufferedReader.fill(BufferedReader.java:161)
[info]   at java.io.BufferedReader.read(BufferedReader.java:182)
[info]   at com.typesafe.config.impl.Tokenizer$TokenIterator.nextCharRaw(Tokenizer.java:156)
[info]   at com.typesafe.config.impl.Tokenizer$TokenIterator.nextCharAfterWhitespace(Tokenizer.java:211)
[info]   ...
```

**Comment by francisbrosnan** [comment]
Solved the issue by closing all java instances (including compilation server loaded in memory). After that, everything worked without error.
